// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ML.Model
{
    public class ModelInput
    {
        [ColumnName("Eye_Left_Blink"), LoadColumn(0)]
        public float Eye_Left_Blink { get; set; }


        [ColumnName("Eye_Left_Wide"), LoadColumn(1)]
        public float Eye_Left_Wide { get; set; }


        [ColumnName("Eye_Left_Right"), LoadColumn(2)]
        public float Eye_Left_Right { get; set; }


        [ColumnName("Eye_Left_Left"), LoadColumn(3)]
        public float Eye_Left_Left { get; set; }


        [ColumnName("Eye_Left_Up"), LoadColumn(4)]
        public float Eye_Left_Up { get; set; }


        [ColumnName("Eye_Left_Down"), LoadColumn(5)]
        public float Eye_Left_Down { get; set; }


        [ColumnName("Eye_Right_Blink"), LoadColumn(6)]
        public float Eye_Right_Blink { get; set; }


        [ColumnName("Eye_Right_Wide"), LoadColumn(7)]
        public float Eye_Right_Wide { get; set; }


        [ColumnName("Eye_Right_Right"), LoadColumn(8)]
        public float Eye_Right_Right { get; set; }


        [ColumnName("Eye_Right_Left"), LoadColumn(9)]
        public float Eye_Right_Left { get; set; }


        [ColumnName("Eye_Right_Up"), LoadColumn(10)]
        public float Eye_Right_Up { get; set; }


        [ColumnName("Eye_Right_Down"), LoadColumn(11)]
        public float Eye_Right_Down { get; set; }


        [ColumnName("Eye_Frown"), LoadColumn(12)]
        public float Eye_Frown { get; set; }


        [ColumnName("Eye_Left_Squeeze"), LoadColumn(13)]
        public float Eye_Left_Squeeze { get; set; }


        [ColumnName("Eye_Right_Squeeze"), LoadColumn(14)]
        public float Eye_Right_Squeeze { get; set; }


        [ColumnName("Max"), LoadColumn(15)]
        public float Max { get; set; }


        [ColumnName("None"), LoadColumn(16)]
        public float None { get; set; }


        [ColumnName("l_pupil_diameter"), LoadColumn(17)]
        public float L_pupil_diameter { get; set; }


        [ColumnName("r_pupil_diameter"), LoadColumn(18)]
        public float R_pupil_diameter { get; set; }


        [ColumnName("Jaw_Right"), LoadColumn(19)]
        public float Jaw_Right { get; set; }


        [ColumnName("Jaw_Left"), LoadColumn(20)]
        public float Jaw_Left { get; set; }


        [ColumnName("Jaw_Forward"), LoadColumn(21)]
        public float Jaw_Forward { get; set; }


        [ColumnName("Jaw_Open"), LoadColumn(22)]
        public float Jaw_Open { get; set; }


        [ColumnName("Mouth_Ape_Shape"), LoadColumn(23)]
        public float Mouth_Ape_Shape { get; set; }


        [ColumnName("Mouth_Upper_Right"), LoadColumn(24)]
        public float Mouth_Upper_Right { get; set; }


        [ColumnName("Mouth_Upper_Left"), LoadColumn(25)]
        public float Mouth_Upper_Left { get; set; }


        [ColumnName("Mouth_Lower_Right"), LoadColumn(26)]
        public float Mouth_Lower_Right { get; set; }


        [ColumnName("Mouth_Lower_Left"), LoadColumn(27)]
        public float Mouth_Lower_Left { get; set; }


        [ColumnName("Mouth_Upper_Overturn"), LoadColumn(28)]
        public float Mouth_Upper_Overturn { get; set; }


        [ColumnName("Mouth_Lower_Overturn"), LoadColumn(29)]
        public float Mouth_Lower_Overturn { get; set; }


        [ColumnName("Mouth_Pout"), LoadColumn(30)]
        public float Mouth_Pout { get; set; }


        [ColumnName("Mouth_Smile_Right"), LoadColumn(31)]
        public float Mouth_Smile_Right { get; set; }


        [ColumnName("Mouth_Smile_Left"), LoadColumn(32)]
        public float Mouth_Smile_Left { get; set; }


        [ColumnName("Mouth_Sad_Right"), LoadColumn(33)]
        public float Mouth_Sad_Right { get; set; }


        [ColumnName("Mouth_Sad_Left"), LoadColumn(34)]
        public float Mouth_Sad_Left { get; set; }


        [ColumnName("Cheek_Puff_Right"), LoadColumn(35)]
        public float Cheek_Puff_Right { get; set; }


        [ColumnName("Cheek_Puff_Left"), LoadColumn(36)]
        public float Cheek_Puff_Left { get; set; }


        [ColumnName("Cheek_Suck"), LoadColumn(37)]
        public float Cheek_Suck { get; set; }


        [ColumnName("Mouth_Upper_UpRight"), LoadColumn(38)]
        public float Mouth_Upper_UpRight { get; set; }


        [ColumnName("Mouth_Upper_UpLeft"), LoadColumn(39)]
        public float Mouth_Upper_UpLeft { get; set; }


        [ColumnName("Mouth_Lower_DownRight"), LoadColumn(40)]
        public float Mouth_Lower_DownRight { get; set; }


        [ColumnName("Mouth_Lower_DownLeft"), LoadColumn(41)]
        public float Mouth_Lower_DownLeft { get; set; }


        [ColumnName("Mouth_Upper_Inside"), LoadColumn(42)]
        public float Mouth_Upper_Inside { get; set; }


        [ColumnName("Mouth_Lower_Inside"), LoadColumn(43)]
        public float Mouth_Lower_Inside { get; set; }


        [ColumnName("Mouth_Lower_Overlay"), LoadColumn(44)]
        public float Mouth_Lower_Overlay { get; set; }


        [ColumnName("Tongue_LongStep1"), LoadColumn(45)]
        public float Tongue_LongStep1 { get; set; }


        [ColumnName("Tongue_Left"), LoadColumn(46)]
        public float Tongue_Left { get; set; }


        [ColumnName("Tongue_Right"), LoadColumn(47)]
        public float Tongue_Right { get; set; }


        [ColumnName("Tongue_Up"), LoadColumn(48)]
        public float Tongue_Up { get; set; }


        [ColumnName("Tongue_Down"), LoadColumn(49)]
        public float Tongue_Down { get; set; }


        [ColumnName("Tongue_Roll"), LoadColumn(50)]
        public float Tongue_Roll { get; set; }


        [ColumnName("Tongue_LongStep2"), LoadColumn(51)]
        public float Tongue_LongStep2 { get; set; }


        [ColumnName("Tongue_UpRight_Morph"), LoadColumn(52)]
        public float Tongue_UpRight_Morph { get; set; }


        [ColumnName("Tongue_UpLeft_Morph"), LoadColumn(53)]
        public float Tongue_UpLeft_Morph { get; set; }


        [ColumnName("Tongue_DownRight_Morph"), LoadColumn(54)]
        public float Tongue_DownRight_Morph { get; set; }


        [ColumnName("Tongue_DownLeft_Morph"), LoadColumn(55)]
        public float Tongue_DownLeft_Morph { get; set; }


        [ColumnName("emotion"), LoadColumn(56)]
        public string Emotion { get; set; }


    }
}
